// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljckqlfoptkahyrdmpml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqY2txbGZvcHRrYWh5cmRtcG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDc2MzYsImV4cCI6MjA2NDQyMzYzNn0.R63WL-3s8LwnsBezkb2yjkHZmtMcLj5r86tU2qqVb8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);